<?php
/*
*******************************************************************************
* METEOBRIDGE / CUMULUS REALTIME.TXT GENERATOR FOR WS40 WORDPRESS PLUGIN       *
*******************************************************************************

Copyright 2026 Gael PHILIPPOT gael@philippot-huang.com

This code is available under GNU General Public License v2.0.

*******************************************************************************
Purpose
*******************************************************************************
This program generates a Cumulus-compatible realtime.txt file for the WS40
WordPress plugin from the latest Ecowitt structured JSON file.

Input:
    - data/latest.json          created by ecowitt-upload.php V2
    - config.ini                runtime configuration, paths, timezone
    - ecowitt-map.json          alias map used as fallback when latest.json was
                                generated by an older uploader or lacks a metric

Output:
    - data/realtime.txt         Cumulus realtime.txt, one space-separated line
    - data/realtime-state.json  daily state for min/max, windrun, yesterday rain
    - log/YYYY-MM-DD.log        optional action/error log

It can be called either:
    - by cron, e.g. every minute
    - by ecowitt-upload.php after a successful upload

Recommended architecture:
    GW3000/WS90 -> ecowitt-upload.php V2 -> latest.json -> generate-realtime.php V2 -> realtime.txt

The station/gateway should ideally run in UTC. This script converts station UTC
time to the local timezone defined in config.ini for display, daily reset and
min/max timestamps.

*******************************************************************************
Version:
    2.00  :  2026-07-08  config.ini + ecowitt-map.json architecture
                            - reads paths/timezone from config.ini
                            - reads ecowitt-map.json for fallback metric decoding
                            - supports latest.json V2 and older latest.json files
                            - keeps WS40 field alignment from V1.02
                            - uses station UTC time converted to local timezone
                            - namespace isolated for safe require/require_once usage
    1.02  :  2026-07-07  WS40 field-alignment fixes (windGust, ET, humidex, native
                         max daily gust, tracked solar max, configurable timezone)
    1.01  :  2026-07-04  Minor correction for logging purpose
    1.00  :  2026-07-03  First release

*/

declare(strict_types=1);

namespace GenerateRealtime;

const VERSION = '2.00';
const DEFAULT_CONFIG_FILE = 'config.ini';
const DEFAULT_MAP_FILE = 'ecowitt-map.json';

main();

function main(): void
{
    $baseDir = __DIR__;

    try {
        $config = load_config($baseDir);

        $timezoneId = (string)cfg($config, 'general', 'timezone', 'UTC');
        $timezone = make_timezone($timezoneId);
        date_default_timezone_set($timezone->getName());

        $dataDir = resolve_path((string)cfg($config, 'paths', 'data_dir', 'data'), $baseDir);
        $logDir  = resolve_path((string)cfg($config, 'paths', 'log_dir', 'log'), $baseDir);
        ensure_dir($dataDir);
        ensure_dir($logDir);

        $writeActionLog = cfg_bool($config, 'logging', 'write_action_log', true);

        $mappingPath = resolve_path((string)cfg($config, 'paths', 'mapping_file', DEFAULT_MAP_FILE), $baseDir);
        $mapping = load_json_file($mappingPath);

        $latestFile = resolve_realtime_path($config, 'latest_file', $dataDir . '/latest.json', $baseDir, $dataDir);
        $stateFile  = resolve_realtime_path($config, 'state_file',  $dataDir . '/realtime-state.json', $baseDir, $dataDir);
        $outputFile = resolve_realtime_path($config, 'output_file', $dataDir . '/realtime.txt', $baseDir, $dataDir);

        if (!is_file($latestFile)) {
            http_response_code(500);
            action_log($logDir, 'generate-realtime V2 - latest.json not found: ' . $latestFile, $writeActionLog, $timezone);
            respond('latest.json not found', 500);
        }

        $data = load_json_file($latestFile);
        $metric = is_array($data['metric'] ?? null) ? $data['metric'] : [];
        $raw = is_array($data['raw'] ?? null) ? $data['raw'] : [];
        $profile = is_array($data['profile'] ?? null) ? $data['profile'] : [];

        action_log($logDir, 'generate-realtime V2 - parsing latest.json', $writeActionLog, $timezone);

        $nowLocal = resolve_observation_time($data, $metric, $timezone, (string)cfg($config, 'realtime_generator', 'time_source', 'station_time_utc'));
        $nowTs = $nowLocal->getTimestamp();
        $today = $nowLocal->format('Y-m-d');
        $timeHM = $nowLocal->format('H:i');

        $sourceLabel = (string)cfg(
            $config,
            'realtime_generator',
            'source_label',
            string_value($metric, 'model') ?: string_value($profile, 'gateway_model') ?: 'Ecowitt'
        );
        $buildLabel = (string)cfg($config, 'realtime_generator', 'build_label', '2');
        $sunnyThreshold = cfg_float($config, 'realtime_generator', 'sunny_threshold_wm2', 120.0);
        $sensorContactLost = (string)cfg($config, 'realtime_generator', 'sensor_contact_lost', '0');
        $forecastNumber = (string)cfg($config, 'realtime_generator', 'forecast_number', '0');
        $daylightMode = strtolower((string)cfg($config, 'realtime_generator', 'daylight_mode', 'auto_by_solar'));
        $etValue = (string)cfg($config, 'realtime_generator', 'et_value', '--');
        $pressureTrendValue = cfg_float($config, 'realtime_generator', 'pressure_trend', 0.0);
        $temperatureTrendValue = cfg_float($config, 'realtime_generator', 'temperature_trend', 0.0);
        $sunshineHoursValue = cfg_float($config, 'realtime_generator', 'sunshine_hours', 0.0);

        $tempC        = metric_value($metric, $raw, $mapping, 'temperature_c', 0.0);
        $hum          = metric_value($metric, $raw, $mapping, 'humidity_pct', 0.0);
        $dewC         = metric_value_nullable($metric, $raw, $mapping, 'dewpoint_c') ?? dewpoint_c($tempC, $hum);
        $windKmh      = metric_value($metric, $raw, $mapping, 'wind_speed_kmh', 0.0);
        $gustKmh      = metric_value($metric, $raw, $mapping, 'wind_gust_kmh', 0.0);
        $windDir      = metric_value($metric, $raw, $mapping, 'wind_direction_deg', 0.0);
        $windAvgDir   = metric_value_nullable($metric, $raw, $mapping, 'wind_direction_avg10m_deg') ?? $windDir;
        $rainRate     = metric_value($metric, $raw, $mapping, 'rain_rate_mm_h', 0.0);
        $rainDay      = metric_value($metric, $raw, $mapping, 'rain_day_mm', 0.0);
        $rainMonth    = metric_value($metric, $raw, $mapping, 'rain_month_mm', 0.0);
        $rainYear     = metric_value($metric, $raw, $mapping, 'rain_year_mm', 0.0);
        $rainWeek     = metric_value($metric, $raw, $mapping, 'rain_week_mm', 0.0);
        $hourlyRain   = metric_value($metric, $raw, $mapping, 'rain_hour_mm', 0.0);
        $pressure     = metric_value($metric, $raw, $mapping, 'pressure_relative_hpa', 0.0);
        $solar        = metric_value($metric, $raw, $mapping, 'solar_radiation_wm2', 0.0);
        $uv           = metric_value($metric, $raw, $mapping, 'uv_index', 0.0);
        $indoorTemp   = metric_value($metric, $raw, $mapping, 'indoor_temperature_c', $tempC);
        $indoorHum    = metric_value($metric, $raw, $mapping, 'indoor_humidity_pct', $hum);
        $maxDailyGust = metric_value($metric, $raw, $mapping, 'max_daily_gust_kmh', 0.0);

        $humidex = humidex_c($tempC, $dewC);

        $state = [];
        if (is_file($stateFile)) {
            $stateData = json_decode((string)file_get_contents($stateFile), true);
            $state = is_array($stateData) ? $stateData : [];
        }

        if (($state['date'] ?? '') !== $today) {
            $state = [
                'date' => $today,
                'timezone' => $timezone->getName(),
                'yesterday_rain_mm' => $state['rain_day_mm'] ?? 0.0,

                'temp_high' => $tempC,
                'temp_high_time' => $timeHM,
                'temp_low' => $tempC,
                'temp_low_time' => $timeHM,

                'wind_high' => $windKmh,
                'wind_high_time' => $timeHM,
                'gust_high' => max($gustKmh, $maxDailyGust),
                'gust_high_time' => $timeHM,

                'pressure_high' => $pressure,
                'pressure_high_time' => $timeHM,
                'pressure_low' => $pressure,
                'pressure_low_time' => $timeHM,

                'solar_high' => $solar,
                'windrun_km' => 0.0,
                'last_seen' => $nowTs,
                'rain_day_mm' => $rainDay,
            ];
        }

        $deltaHours = max(0.0, min(1.0, ($nowTs - (int)($state['last_seen'] ?? $nowTs)) / 3600.0));
        $state['windrun_km'] = (float)($state['windrun_km'] ?? 0.0) + ($windKmh * $deltaHours);
        $state['last_seen'] = $nowTs;
        $state['rain_day_mm'] = $rainDay;
        $state['timezone'] = $timezone->getName();

        update_high_low($state, 'temp_high', 'temp_high_time', $tempC, $timeHM, true);
        update_high_low($state, 'temp_low', 'temp_low_time', $tempC, $timeHM, false);
        update_high_low($state, 'wind_high', 'wind_high_time', $windKmh, $timeHM, true);

        // Prefer the gateway's native max daily gust when it exceeds the current gust.
        $gustCandidate = $maxDailyGust > $gustKmh ? $maxDailyGust : $gustKmh;
        update_high_low($state, 'gust_high', 'gust_high_time', $gustCandidate, $timeHM, true);

        // Track today's peak solar radiation for the solar-max field.
        if (!isset($state['solar_high']) || $solar > (float)$state['solar_high']) {
            $state['solar_high'] = $solar;
        }

        update_high_low($state, 'pressure_high', 'pressure_high_time', $pressure, $timeHM, true);
        update_high_low($state, 'pressure_low', 'pressure_low_time', $pressure, $timeHM, false);

        $windChill = metric_value_nullable($metric, $raw, $mapping, 'windchill_c') ?? windchill_c($tempC, $windKmh);
        $heatIndex = metric_value_nullable($metric, $raw, $mapping, 'heatindex_c') ?? heatindex_c($tempC, $hum);
        $feelsLike = metric_value_nullable($metric, $raw, $mapping, 'feelslike_c') ?? ($tempC <= 10.0 ? $windChill : $heatIndex);

        $cloudBaseFt = max(0.0, (($tempC - $dewC) / 2.5) * 1000.0 * 3.28084);
        $isSunny = $solar > $sunnyThreshold ? 1 : 0;
        $isDaylight = daylight_value($daylightMode, $solar, $sunnyThreshold, $nowLocal);

        /*
         * Cumulus realtime.txt.
         * One line with space separator. Field alignment intentionally follows V1.02.
         */
        $fields = [
            $nowLocal->format('d/m/y'),               // 1 Date
            $nowLocal->format('H:i:s'),               // 2 Time
            n($tempC),                                // 3 Outdoor temp
            (string)round($hum),                      // 4 Outdoor humidity
            n($dewC),                                 // 5 Dew point
            n($windKmh),                              // 6 Wind speed average
            n($gustKmh),                              // 7 Gust (WS40 maps this position to windGust)
            (string)round($windDir),                  // 8 Wind bearing
            n($rainRate),                             // 9 Rain rate
            n($rainDay),                              // 10 Rain today
            n($pressure),                             // 11 Pressure
            compass($windDir),                        // 12 Current wind direction
            (string)beaufort_from_kmh($windKmh),      // 13 Beaufort
            'km/h',                                   // 14 Wind unit
            'C',                                      // 15 Temp unit
            'hPa',                                    // 16 Pressure unit
            'mm',                                     // 17 Rain unit
            n((float)$state['windrun_km']),           // 18 Wind run today
            n($pressureTrendValue, 1),                // 19 Pressure trend
            n($rainMonth),                            // 20 Monthly rain
            n($rainYear),                             // 21 Yearly rain
            n((float)($state['yesterday_rain_mm'] ?? 0.0)), // 22 Yesterday rain
            n($indoorTemp),                           // 23 Indoor temp
            (string)round($indoorHum),                // 24 Indoor humidity
            n($windChill),                            // 25 Wind chill
            n($temperatureTrendValue, 1),             // 26 Temp trend
            n((float)$state['temp_high']),            // 27 High temp today
            (string)$state['temp_high_time'],         // 28 Time high temp
            n((float)$state['temp_low']),             // 29 Low temp today
            (string)$state['temp_low_time'],          // 30 Time low temp
            n((float)$state['wind_high']),            // 31 High wind speed today
            (string)$state['wind_high_time'],         // 32 Time high wind
            n((float)$state['gust_high']),            // 33 High gust today
            (string)$state['gust_high_time'],         // 34 Time high gust
            n((float)$state['pressure_high']),        // 35 High pressure
            (string)$state['pressure_high_time'],     // 36 Time high pressure
            n((float)$state['pressure_low']),         // 37 Low pressure
            (string)$state['pressure_low_time'],      // 38 Time low pressure
            sanitize_realtime_token($sourceLabel),    // 39 Version/source
            sanitize_realtime_token($buildLabel),     // 40 Build
            n($gustKmh),                              // 41 10-min high gust / current gust fallback
            n($heatIndex),                            // 42 Heat index
            n($humidex),                              // 43 Humidex
            n($uv, 1),                                // 44 UV
            $etValue,                                 // 45 ET, usually '--' so WS40 computes FAO-56 estimate
            (string)round($solar),                    // 46 Solar radiation
            (string)round($windAvgDir),               // 47 Average bearing
            n($hourlyRain),                           // 48 Rain last hour
            sanitize_realtime_token($forecastNumber), // 49 Forecast number
            (string)$isDaylight,                      // 50 Is daylight
            sanitize_realtime_token($sensorContactLost), // 51 Sensor contact lost
            compass($windAvgDir),                     // 52 Average wind direction
            (string)round($cloudBaseFt),              // 53 Cloud base
            'ft',                                     // 54 Cloud base unit
            n($feelsLike),                            // 55 Apparent temp
            n($sunshineHoursValue, 1),                // 56 Sunshine hours
            (string)round(max((float)($state['solar_high'] ?? $solar), 0)), // 57 Solar max today
            (string)$isSunny,                         // 58 Is sunny
            n($feelsLike),                            // 59 Feels like
            n($rainWeek),                             // 60 Rain week, Cumulus MX recent
        ];

        write_json_atomic($stateFile, $state);
        write_text_atomic($outputFile, implode(' ', $fields) . "\n");

        action_log($logDir, 'generate-realtime V2 - realtime.txt updated', $writeActionLog, $timezone);
        respond('OK', 200);
    } catch (\Throwable $e) {
        error_log('generate-realtime V2 fatal error: ' . $e->getMessage());
        http_response_code(500);
        echo "SERVER ERROR\n";
    }
}

function load_config(string $baseDir): array
{
    $configPath = getenv('ECOWITT_CONFIG');

    if (!is_string($configPath) || trim($configPath) === '') {
        $configPath = $baseDir . '/' . DEFAULT_CONFIG_FILE;
    }

    if (!is_file($configPath)) {
        throw new \RuntimeException('Configuration file not found: ' . $configPath);
    }

    $config = parse_ini_file($configPath, true, INI_SCANNER_TYPED);
    if (!is_array($config)) {
        throw new \RuntimeException('Invalid configuration file: ' . $configPath);
    }

    return $config;
}

function cfg(array $config, string $section, string $key, mixed $default = null): mixed
{
    return $config[$section][$key] ?? $default;
}

function cfg_bool(array $config, string $section, string $key, bool $default): bool
{
    $value = cfg($config, $section, $key, $default);

    if (is_bool($value)) {
        return $value;
    }
    if (is_int($value) || is_float($value)) {
        return $value !== 0;
    }
    if (is_string($value)) {
        return in_array(strtolower(trim($value)), ['1', 'true', 'yes', 'on', 'enabled'], true);
    }

    return $default;
}

function cfg_float(array $config, string $section, string $key, float $default): float
{
    $value = cfg($config, $section, $key, $default);
    if (is_int($value) || is_float($value)) {
        return (float)$value;
    }
    if (is_string($value)) {
        $n = number_from_mixed($value);
        return $n ?? $default;
    }
    return $default;
}

function make_timezone(string $timezoneId): \DateTimeZone
{
    try {
        return new \DateTimeZone($timezoneId !== '' ? $timezoneId : 'UTC');
    } catch (\Throwable) {
        return new \DateTimeZone('UTC');
    }
}

function resolve_path(string $path, string $baseDir): string
{
    if ($path === '') {
        return $baseDir;
    }
    if (str_starts_with($path, '/')) {
        return $path;
    }
    return rtrim($baseDir, '/') . '/' . $path;
}

function resolve_realtime_path(array $config, string $key, string $default, string $baseDir, string $dataDir): string
{
    $value = (string)cfg($config, 'realtime_generator', $key, '');
    if ($value === '') {
        return $default;
    }
    if (str_starts_with($value, '/')) {
        return $value;
    }

    // For realtime files, relative paths are resolved from data_dir by default.
    // Use ../ if you intentionally need to escape it.
    return rtrim($dataDir, '/') . '/' . $value;
}

function ensure_dir(string $dir): void
{
    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
        throw new \RuntimeException('Unable to create directory: ' . $dir);
    }
}

function load_json_file(string $path): array
{
    if (!is_file($path)) {
        throw new \RuntimeException('JSON file not found: ' . $path);
    }

    $json = file_get_contents($path);
    if ($json === false) {
        throw new \RuntimeException('Unable to read JSON file: ' . $path);
    }

    $data = json_decode($json, true);
    if (!is_array($data)) {
        throw new \RuntimeException('Invalid JSON file ' . $path . ': ' . json_last_error_msg());
    }

    return $data;
}

function write_json_atomic(string $path, array $data): void
{
    $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE);
    if ($json === false) {
        throw new \RuntimeException('Unable to encode JSON for: ' . $path);
    }
    write_text_atomic($path, $json . "\n");
}

function write_text_atomic(string $path, string $content): void
{
    $dir = dirname($path);
    ensure_dir($dir);

    $tmp = tempnam($dir, '.tmp-');
    if ($tmp === false) {
        throw new \RuntimeException('Unable to create temporary file in: ' . $dir);
    }

    try {
        if (file_put_contents($tmp, $content, LOCK_EX) === false) {
            throw new \RuntimeException('Unable to write temporary file: ' . $tmp);
        }
        if (!rename($tmp, $path)) {
            throw new \RuntimeException('Unable to move temporary file to: ' . $path);
        }
    } finally {
        if (is_file($tmp)) {
            @unlink($tmp);
        }
    }
}

function action_log(string $logDir, string $message, bool $enabled, \DateTimeZone $timezone): void
{
    if (!$enabled) {
        return;
    }

    ensure_dir($logDir);
    $now = new \DateTimeImmutable('now', $timezone);
    $line = $now->format('Y-m-d H:i:s T') . ' - ' . $message . PHP_EOL;

    file_put_contents(
        rtrim($logDir, '/') . '/' . $now->format('Y-m-d') . '.log',
        $line,
        FILE_APPEND | LOCK_EX
    );
}

function respond(string $message, int $status): never
{
    if (!headers_sent()) {
        http_response_code($status);
        header('Content-Type: text/plain; charset=utf-8');
    }

    echo $message . "\n";
    exit;
}

function resolve_observation_time(array $data, array $metric, \DateTimeZone $localTz, string $timeSource): \DateTimeImmutable
{
    $timeSource = strtolower(trim($timeSource));

    $candidates = match ($timeSource) {
        'generated_at_utc' => [$data['generated_at_utc'] ?? null, $metric['received_at_utc'] ?? null, $metric['station_time_utc'] ?? null],
        'received_at_utc' => [$metric['received_at_utc'] ?? null, $data['generated_at_utc'] ?? null, $metric['station_time_utc'] ?? null],
        'server_local', 'now' => [],
        default => [$metric['station_time_utc'] ?? null, $data['station_time_utc'] ?? null, $metric['received_at_utc'] ?? null, $data['generated_at_utc'] ?? null],
    };

    foreach ($candidates as $candidate) {
        if (!is_string($candidate) || trim($candidate) === '') {
            continue;
        }

        $dt = parse_datetime_as_utc($candidate);
        if ($dt !== null) {
            return $dt->setTimezone($localTz);
        }
    }

    return new \DateTimeImmutable('now', $localTz);
}

function parse_datetime_as_utc(string $value): ?\DateTimeImmutable
{
    $value = trim($value);
    if ($value === '') {
        return null;
    }

    try {
        // Ecowitt dateutc commonly arrives as "YYYY-mm-dd HH:ii:ss" without timezone.
        if (preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/', $value)) {
            return new \DateTimeImmutable($value, new \DateTimeZone('UTC'));
        }

        $dt = new \DateTimeImmutable($value);
        return $dt->setTimezone(new \DateTimeZone('UTC'));
    } catch (\Throwable) {
        return null;
    }
}

function metric_value(array $metric, array $raw, array $mapping, string $metricName, float $default = 0.0): float
{
    return metric_value_nullable($metric, $raw, $mapping, $metricName) ?? $default;
}

function metric_value_nullable(array $metric, array $raw, array $mapping, string $metricName): ?float
{
    $direct = number_from_array($metric, $metricName);
    if ($direct !== null) {
        return $direct;
    }

    $definition = $mapping['fields'][$metricName] ?? null;
    if (is_array($definition)) {
        $result = extract_numeric_from_sources($raw, $definition, null);
        if ($result['found']) {
            return $result['value'];
        }
    }

    return null;
}

function string_value(array $data, string $key): ?string
{
    if (!array_key_exists($key, $data)) {
        return null;
    }
    $text = trim((string)$data[$key]);
    return $text === '' ? null : $text;
}

function number_from_array(array $data, string $key): ?float
{
    if (!array_key_exists($key, $data)) {
        return null;
    }
    return number_from_mixed($data[$key]);
}

function number_from_mixed(mixed $value): ?float
{
    if ($value === null) {
        return null;
    }

    if (is_int($value) || is_float($value)) {
        $float = (float)$value;
        return is_finite($float) ? $float : null;
    }

    $text = trim((string)$value);
    if ($text === '') {
        return null;
    }

    $lower = strtolower($text);
    if (in_array($lower, ['--', '---', 'null', 'nan', 'n/a', 'na'], true)) {
        return null;
    }

    $text = str_replace(',', '.', $text);
    if (!is_numeric($text)) {
        return null;
    }

    $float = (float)$text;
    return is_finite($float) ? $float : null;
}

function extract_numeric_from_sources(array $payload, array $definition, ?string $channel): array
{
    foreach (($definition['sources'] ?? []) as $source) {
        if (!is_array($source)) {
            continue;
        }

        $key = source_key($source, $channel);
        if ($key === null || !array_key_exists($key, $payload)) {
            continue;
        }

        $value = number_from_array($payload, $key);
        if ($value === null) {
            continue;
        }

        $fromUnit = (string)($source['unit'] ?? 'raw');
        $targetUnit = (string)($definition['target_unit'] ?? $fromUnit);
        $converted = convert_unit($value, $fromUnit, $targetUnit);
        $decimals = (int)($definition['decimals'] ?? 2);

        return [
            'found' => true,
            'value' => round_value($converted, $decimals),
            'source_key' => $key,
            'source_unit' => $fromUnit,
            'target_unit' => $targetUnit,
        ];
    }

    return ['found' => false, 'value' => null];
}

function source_key(array $source, ?string $channel): ?string
{
    if (isset($source['key'])) {
        return (string)$source['key'];
    }
    if (isset($source['key_pattern']) && $channel !== null) {
        return str_replace('{channel}', $channel, (string)$source['key_pattern']);
    }
    return null;
}

function convert_unit(float $value, string $from, string $to): float
{
    if ($from === $to || $to === '' || $from === 'raw' || $to === 'raw') {
        return $value;
    }

    return match ($from . '>' . $to) {
        'F>C' => ($value - 32.0) * 5.0 / 9.0,
        'C>F' => ($value * 9.0 / 5.0) + 32.0,
        'inHg>hPa' => $value * 33.8638866667,
        'hPa>inHg' => $value / 33.8638866667,
        'mph>km/h' => $value * 1.609344,
        'km/h>mph' => $value / 1.609344,
        'm/s>km/h' => $value * 3.6,
        'km/h>m/s' => $value / 3.6,
        'inch>mm' => $value * 25.4,
        'mm>inch' => $value / 25.4,
        'inch/h>mm/h' => $value * 25.4,
        'mm/h>inch/h' => $value / 25.4,
        'mi>km' => $value * 1.609344,
        'km>mi' => $value / 1.609344,
        default => $value,
    };
}

function round_value(float $value, int $decimals): int|float
{
    if ($decimals <= 0) {
        return (int)round($value);
    }
    return round($value, $decimals);
}

function n(?float $value, int $decimals = 1): string
{
    return number_format($value ?? 0.0, $decimals, '.', '');
}

function compass(?float $deg): string
{
    if ($deg === null) {
        return '---';
    }

    $deg = fmod($deg, 360.0);
    if ($deg < 0) {
        $deg += 360.0;
    }

    $dirs = [
        'N', 'NNE', 'NE', 'ENE',
        'E', 'ESE', 'SE', 'SSE',
        'S', 'SSW', 'SW', 'WSW',
        'W', 'WNW', 'NW', 'NNW'
    ];

    $i = (int)round($deg / 22.5) % 16;
    return $dirs[$i];
}

function beaufort_from_kmh(float $kmh): int
{
    $limits = [1, 6, 12, 20, 29, 39, 50, 62, 75, 89, 103, 118];
    foreach ($limits as $i => $limit) {
        if ($kmh < $limit) {
            return $i;
        }
    }
    return 12;
}

function dewpoint_c(float $tempC, float $humidity): float
{
    if ($humidity <= 0.0) {
        return $tempC;
    }

    $humidity = max(1.0, min(100.0, $humidity));
    $a = 17.27;
    $b = 237.7;
    $alpha = (($a * $tempC) / ($b + $tempC)) + log($humidity / 100.0);

    return ($b * $alpha) / ($a - $alpha);
}

function windchill_c(float $tempC, float $windKmh): float
{
    if ($tempC > 10.0 || $windKmh <= 4.8) {
        return $tempC;
    }

    return 13.12
        + 0.6215 * $tempC
        - 11.37 * pow($windKmh, 0.16)
        + 0.3965 * $tempC * pow($windKmh, 0.16);
}

function heatindex_c(float $tempC, float $humidity): float
{
    $tempF = ($tempC * 9.0 / 5.0) + 32.0;

    if ($tempF < 80.0) {
        return $tempC;
    }

    $hiF =
        -42.379
        + 2.04901523 * $tempF
        + 10.14333127 * $humidity
        - 0.22475541 * $tempF * $humidity
        - 0.00683783 * $tempF * $tempF
        - 0.05481717 * $humidity * $humidity
        + 0.00122874 * $tempF * $tempF * $humidity
        + 0.00085282 * $tempF * $humidity * $humidity
        - 0.00000199 * $tempF * $tempF * $humidity * $humidity;

    return ($hiF - 32.0) * 5.0 / 9.0;
}

/*
 * Canadian humidex from air temperature and dew point, both in °C.
 * Below about 20 °C, returning air temperature avoids absurd cool-weather values.
 */
function humidex_c(float $tempC, float $dewC): float
{
    if ($tempC < 20.0) {
        return $tempC;
    }

    $dewK = $dewC + 273.16;
    if ($dewK <= 0.0) {
        return $tempC;
    }

    $e = 6.11 * exp(5417.7530 * ((1.0 / 273.16) - (1.0 / $dewK)));
    $h = $tempC + 0.5555 * ($e - 10.0);

    return $h < $tempC ? $tempC : $h;
}

function update_high_low(array &$state, string $valueKey, string $timeKey, float $candidate, string $timeHM, bool $higherWins): void
{
    if (!isset($state[$valueKey])) {
        $state[$valueKey] = $candidate;
        $state[$timeKey] = $timeHM;
        return;
    }

    $current = (float)$state[$valueKey];
    if (($higherWins && $candidate > $current) || (!$higherWins && $candidate < $current)) {
        $state[$valueKey] = $candidate;
        $state[$timeKey] = $timeHM;
    }
}

function daylight_value(string $mode, float $solar, float $sunnyThreshold, \DateTimeImmutable $nowLocal): int
{
    return match ($mode) {
        'always_1', 'always_true', 'true' => 1,
        'always_0', 'always_false', 'false' => 0,
        'auto_by_hour' => ((int)$nowLocal->format('G') >= 6 && (int)$nowLocal->format('G') < 22) ? 1 : 0,
        default => $solar > max(1.0, $sunnyThreshold * 0.1) ? 1 : 0,
    };
}

function sanitize_realtime_token(string $value): string
{
    $value = trim($value);
    if ($value === '') {
        return '-';
    }

    // realtime.txt is space-separated, so replace spaces/control chars.
    return preg_replace('/\s+/', '_', $value) ?? '-';
}
